### ISSUE TITLE
Bug in `dt_seq_helper`

### ISSUE THREAD

**Issue by sergejlazuk** [krose/entsoeapi#27] opened 2024-09-22 09:45 UTC
There seems to be a bug in `dt_seq_helper` func:

```
by <- dplyr::case_when(seq_resolution == "PT1M" ~ "1 min",
                          seq_resolution == "PT15M" ~ "15 mins",
                          seq_resolution == "PT30M" ~ "30 mins",
                          seq_resolution == "PT60M" ~ "1 hour",
                          seq_resolution == "P1D" ~ "1 DSTday",
                          seq_resolution == "P7D" ~ "7 DSTdays",
                          seq_resolution == "P1Y" ~ "1 year",
                          .default = "n/a")

  Error in `dplyr::case_when()`:
  ! Case 8 (`seq_resolution == "PT1M" ~ "1 min"`) must be a two-sided formula, not a character vector.

```

It works if I remove `.default` in the end.

**Comment by sbudai** [comment] 2024-09-22 10:46
Dear sergejlazuk,

The dt_seq_helper() is a not exported function of the package.
Do you use it implicitly by calling exported 'entsoeapi' functions, or you would like to use it independently of the package?
If the earlier one is true, would you provide a reproducible example (what exported function you called with which parameters?).

Thanks & Regards
Sandor

**Comment by sergejlazuk** [comment] 2024-09-22 14:25
Hi Sandor, I was trying to call this function:
```
gen_wind_solar_forecasts(eic = '10YDE-RWENET---I',tidy_output = TRUE)
```

It throwed an error; then I was seeking where it comes from and it seems it comes from  `dt_seq_helper`; there it is caused by `dplyr::case_when`.

I had to remove `.default` from `case_when` and now it works.

I use R 4.2.2 and dplyr version 1.2.2.

Regards,
Sergej

**Comment by sergejlazuk** [comment] 2024-09-24 09:14
No harry!
Thx for maintaining this project,
Sergej


Am Di., 24. Sept. 2024 um 10:15 Uhr schrieb Sandor Budai <
***@***.***>:

**Comment by sbudai** [comment] 2024-10-04 19:29
Hey Sergej,

I have not forgotten it, but I am very busy nowadays. So I ask for more patience.

**Comment by sergejlazuk** [comment] 2024-10-04 19:49
No problem, I understand.


Sandor Budai ***@***.***> schrieb am Fr. 4. Okt. 2024 um
21:30:

**Comment by sbudai** [comment] 2024-10-05 22:11
Hi Sergej,

I was not able to reproduce the error so I was not able to find out the root cause of the problem either. Therefore I added a tryCatch and some debug messages added to `dt_seq_helper()` function. Please, upgrade to the new version (0.7.1.1) and inform me what kind of related error messages you get, if any.

Thanks,
Sandor

**Comment by sergejlazuk** [comment] 2024-10-07 10:21
Ok, I will check.

Thx.

Am So., 6. Okt. 2024 um 00:11 Uhr schrieb Sandor Budai <
***@***.***>:

**Comment by sergejlazuk** [comment] 2024-10-15 12:32
HI Sandor,
I have installed latest version (0.7.1.2) and am using dplyr 1.0.10.
I still get an error, here with exampel from README:

```
load_actual_total(eic = "10Y1001A1001A83F",
+                   period_start = ymd("2020-01-01", tz = "CET"),
+                   period_end = ymd("2020-01-02", tz = "CET")) |>
+   glimpse()
https://web-api.tp.entsoe.eu/api?documentType=A65&processType=A16&outBiddingZone_Domain=10Y1001A1001A83F&periodStart=201912312300&periodEnd=202001012300&securityToken=63a0b5b3-d74a-4093-b8fd-821807415afd ...
downloaded
Case 8 (`seq_resolution == "PT1M" ~ "1 min"`) must be a two-sided formula, not a character vector.
The sequence resolution does not seem to be valid.
Its type is: character
Its structure is:  chr "PT15M"
Error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `dt_seq_helper()`:
! The 'resolution' value of the response is not supported yet.
Please use 'PT1M', 'PT15M', 'PT30M', 'PT60M', 'P1D', 'P7D' or 'P1Y'.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by sbudai** [comment] 2024-10-16 12:19
It is still a mysterious error. (I cannot reproduce.) Now I replaced dplyr::case_when() function with data.table::fcase(). I hope it will be OK on your machine as well. It will be released with the forthcoming 0.7.1.3 version.

**Comment by sergejlazuk** [comment] 2024-10-16 20:44
Thx, I will test it then,

Mit freundlichen Grüßen/Best Regards
S. Lazuk


Sandor Budai ***@***.***> schrieb am Mi. 16. Okt. 2024 um
14:19:

**Comment by sbudai** [comment] 2024-10-22 23:18
The new version is out. I versioned as 0.7.2.0. It contains the hoped error resolution.

**Closed** 2024-12-19 16:38 UTC
